Dev/rafd 277
ThalesGroup/cdap-build pull request #11
Opened 2019-02-04 10:39 UTC by jatinderjawanda

Added cdap-perimeter and ranger auth role in provisioner.

2019-02-04 12:15 UTC, miraj-godha-guavus commented
Hi Jatinder,

Here are few observations/questions, can you please help me understand them:

- Why true is required in Quotes:
ansible/roles/raf/cdap-perimeter-security/deploy/defaults/main.yml

cdap__security_enabled: 'true'
cdap__ssl_external_enabled: 'true'


- Do not checkin sensitive info, they might go with build


cdap__security_authentication_handler_bindDn: "CN=svc-devops,OU=ApplicationObjects,OU=Custom,DC=guavus,DC=com"
cdap__security_authentication_handler_bindPassword: MSWmdT9XZnQwJ9GntCsG
ambari_admin_user: 'admin'
ambari_admin_password: 'Sbe7UGkRBMF8'

- What is this cofiguration?

cdap__cdap_jar_path: "/home/cdap_security.tar"

- We need to enable default values here, as described in RAFD-277

ansible/roles/raf/cdap-perimeter-security/deploy/tasks/main.yml

- What is this file? ansible/roles/raf/cdap-perimeter-security/undeploy/.travis.yml


- How are we undeploying: ansible/roles/raf/cdap-perimeter-security/undeploy/meta/main.yml


- From where are we reading this property: ansible/roles/raf/cdap-ranger-

auth/deploy/templates/ranger-cdap-audit.j2
 <property>
      <name>xasecure.audit.destination.hdfs.dir</name>
      <value>hdfs://{{platform_hadoop_nameservices}}/ranger/audit</value>
    </property>

    

- Incorect peroperty set:
auth/deploy/templates/ranger-cdap-audit.j2

    <property>
      <name>xasecure.audit.jaas.Client.option.principal</name>
      <value>cdap/_HOST@GVS.GGN</value>
    </property>


   

-  Are we sure that ansible will alwyas run on Ranger node? ansible/roles/raf/cdap-ranger-auth/deploy/templates/ranger-cdap-security.j2

    <property>
    <name>ranger.plugin.cdap.policy.rest.url</name>
    <value>http://{{ ansible_nodename }}:6080</value>
    <description>
      URL to Ranger Admin
    </description>


  

-   If we are hardcoding cdapdev as the folder name, we have to ensure that ranger policy is added with the same name. I hope that is taken care.

    <property>
    <name>ranger.plugin.cdap.policy.cache.dir</name>
    <value>/etc/ranger/cdapdev/policycache</value>
    <description>
      Directory where Ranger policies are cached after successful retrieval from the source
    </description>
  </property>

2019-02-18 06:15 UTC, ankur-gupta-guavus requested changes

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/playbooks/raf/cdap-perimeter-security/deploy/main.yml
> +        raf_docker_registry: '{{ docker_default_registry }}'
Do we even need to set these facts for enabling security in CDAP ? I don't see them being used anywhere . Specifically, raf_docker_registry

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/playbooks/raf/cdap-perimeter-security/deploy/main.yml
> +    - management-nodes
Shouldn't we create raf specific host groups inside inventory hosts and use them instead of just using the ones which are present for BPL ? This will help in reducing dependancy on BPL. 

Something like 
[raf-cdap-nodes]
master-nodes ==> This could be default value or just an example in guide for installation on Reflex BPL. 

Let me know what u think.

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/playbooks/raf/cdap-perimeter-security/deploy/main.yml
> +    - cdap_master_nodes: "master-nodes"
Again, much better to define cdap_master_nodes and cdap_management_nodes from inventory . It can be a comment in guide to create these host groups before starting,

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/playbooks/raf/cdap-ranger-auth/deploy/main.yml
> +        raf_docker_registry: '{{ docker_default_registry }}'
Do we even need to set these facts for enabling security in CDAP ? I don't see them being used anywhere . Specifically, raf_docker_registry

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/roles/raf/cdap-perimeter-security/deploy/.travis.yml
> +notifications:
Do you have a CI pipe set for testing ansible ? And hence the .travis.yml ?

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/roles/raf/cdap-perimeter-security/deploy/defaults/main.yml
> +
I would recommend moving above variables to inventory files specific. Some structure like inventory/generated/<stage_type>/<inventory_name>//groups_vars/raf/cdap

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/roles/raf/cdap-perimeter-security/deploy/defaults/main.yml
> +cdap__cdap_jar_path: "/home/cdap_security.tar"
What is this tar ? What this contains and from where user will get this ?

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/roles/raf/cdap-perimeter-security/deploy/tasks/main.yml
> +  shell: "/var/lib/ambari-server/resources/scripts/configs.py -a set -u {{ ambari_admin_user }} -p {{ ambari_admin_password }} -l {{ cdap_loadbalancer_vip }} -n {{ cluster_name }} -c {{ item.config }
Please maintain state with ansible shell module using option "creates" for each property to make this idempotent

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/roles/raf/cdap-perimeter-security/deploy/defaults/main.yml
> +cdap__security_authentication_handler_bindPassword: MSWmdT9XZnQwJ9GntCsG
Lets not store passwords in clear text inside files. We should try and secure them using ansible vault. All the passwords

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/roles/raf/cdap-perimeter-security/deploy/meta/main.yml
> +galaxy_info:
Is this file required ?

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/roles/raf/cdap-perimeter-security/deploy/tasks/main.yml
> +  tags: log
Is this step really necessary ?

2019-02-18 06:15 UTC, ankur-gupta-guavus commented on ansible/roles/raf/cdap-ranger-auth/deploy/defaults/main.yml
> +cdap__ranger_servicedef_cdap: |
Can we store this in some file instead of as a variable ?

2019-02-18 10:53 UTC, jatinderjawanda commented
Changes done as requested.

2019-02-19 09:12 UTC, closed without merging